# Generated by Django 3.2.3 on 2021-05-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Teams'},
        ),
    ]
