# Generated by Django 3.2.3 on 2021-05-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
    ]
