# Generated by Django 3.2.5 on 2021-11-30 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_auto_20211130_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('supplier_email', models.EmailField(max_length=254, unique=True)),
                ('supplier_zip_code', models.CharField(max_length=10)),
                ('supplier_country', django_countries.fields.CountryField(max_length=2)),
                ('supplier_fax', models.BigIntegerField(blank=True, null=True)),
                ('supplier_previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier_ledger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
