# Generated by Django 3.2.5 on 2021-11-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='supplier_full_name',
        ),
    ]
