# Generated by Django 3.2.5 on 2021-11-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_rename_supplier_name_supplier_supplier_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(max_length=100, verbose_name='Supplier Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Supplier Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_fax',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Supplier Fax'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_full_name',
            field=models.CharField(max_length=100, verbose_name='Supplier Full Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Supplier Previous Balance'),
        ),
    ]
