# Generated by Django 3.2.5 on 2021-12-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20211201_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsupplier',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Supplier'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
