# Generated by Django 4.2 on 2023-10-14 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows', models.IntegerField(default=0)),
                ('mac', models.IntegerField(default=0)),
                ('linux', models.IntegerField(default=0)),
                ('android', models.IntegerField(default=0)),
                ('ios', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
            },
        ),
        migrations.CreateModel(
            name='DeviceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, help_text='e.g. Chrome 98, Windows, TECNO KE5, Android', max_length=255, null=True, verbose_name='User Agent')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last activity of the device', null=True, verbose_name='Last Activity')),
                ('ip_address', models.GenericIPAddressField(blank=True, default='', help_text='IP address of the device', null=True, verbose_name='IP Address')),
                ('location', models.CharField(blank=True, help_text='Location of the device', max_length=255, null=True, verbose_name='Location')),
                ('timezone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Timezone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Device Activity',
                'verbose_name_plural': 'Device Activity',
                'ordering': ('-last_activity',),
            },
        ),
    ]
