# Generated by Django 3.2.5 on 2021-11-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier_name',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(default='3156', max_length=4, unique=True),
        ),
    ]
