# Generated by Django 3.2.9 on 2021-12-23 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('purchase', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reutrn_date', models.DateField(default=django.utils.timezone.now)),
                ('additional_information', models.TextField(blank=True, help_text='e.g. My phone has missing headphones', max_length=500, null=True, verbose_name='Additional Information (optional)')),
                ('is_returned', models.BooleanField(default=False)),
                ('return_reason', models.CharField(choices=[('item is defective or not working', 'Item is defective or not working'), ('item or accessory is missing in the', 'Item or accessory is missing in the'), ('item has missing freebie', 'Item has missing freebie'), ('item does not match decription or picture', 'Item does not match decription or picture'), ('i did not order this size', 'I did not order this size'), ('i received the wrong item', 'I received the wrong item'), ('item does not fit me', 'Item does not fit me'), ("don't want to item anymore", "Don't want to item anymore"), ('item is damaged/broken/has dent or scratches', 'Item is damaged/broken/has dent or scratches')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]
