# Generated by Django 4.2.6 on 2023-10-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='return',
            name='supplier',
        ),
    ]
