# Generated by Django 3.2.5 on 2021-12-19 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20211219_1311'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase'),
        ),
        migrations.AddField(
            model_name='return',
            name='reutrn_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
