# Generated by Django 4.2.6 on 2023-10-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_remove_return_customer_remove_return_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='purchase',
        ),
    ]
