# Generated by Django 3.2.5 on 2021-12-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_product_product_code'),
        ('customers', '0012_alter_ledger_voucher_no'),
        ('suppliers', '0005_auto_20211214_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_damaged', models.BooleanField(default=False)),
                ('damaged_date', models.DateField(auto_now_add=True)),
                ('damaged_reason', models.CharField(choices=[('broken', 'Broken'), ('missing', 'Missing')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]
