# Generated by Django 4.2 on 2023-05-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer_notified', models.BooleanField(default=False)),
                ('is_supplier_notified', models.BooleanField(default=False)),
                ('damaged_date', models.DateField()),
                ('damaged_reason', models.CharField(choices=[('broken', 'Broken'), ('missing', 'Missing'), ('expiry dates over', 'Expiry Dates over'), ('empty', 'Empty')], max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]
