# Generated by Django 3.2.5 on 2021-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='is_damaged',
        ),
        migrations.AlterField(
            model_name='damage',
            name='damaged_date',
            field=models.DateField(),
        ),
    ]
