# Generated by Django 3.2.9 on 2021-12-23 14:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=25, verbose_name='Name of Account')),
                ('account_description', models.TextField(verbose_name='Descrition')),
                ('country', django_countries.fields.CountryField(default='BD', max_length=2)),
                ('divistion', models.CharField(choices=[('dhaka', 'Dhaka'), ('sylhet', 'Sylhet'), ('barishal', 'Barishal'), ('chattogram', 'Chattogram'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], max_length=25, verbose_name='Division')),
                ('districts', models.CharField(choices=[('dhaka', 'Dhaka'), ('faridpur', 'Faridpur'), ('gazipur', 'Gazipur'), ('gopalganj', 'Gopalganj'), ('jamalpur', 'Jamalpur'), ('kishoreganj', 'Kishoreganj'), ('madaripur', 'Madaripur'), ('manikganj', 'Manikganj'), ('munshiganj', 'Munshiganj'), ('narayanganj', 'Narayanganj'), ('narsingdi', 'Narsingdi'), ('netrokona', 'Netrokona'), ('rajbari', 'Rajbari'), ('shariatpur', 'Shariatpur'), ('sherpur', 'Sherpur'), ('tangail', 'Tangail'), ('bogra', 'Bogra'), ('joypurhat', 'Joypurhat'), ('naogaon', 'Naogaon'), ('natore', 'Natore'), ('nawabganj', 'Nawabganj'), ('pabna', 'Pabna'), ('rajshahi', 'Rajshahi'), ('sirajganj', 'Sirajganj'), ('dinajpur', 'Dinajpur'), ('gaibandha', 'Gaibandha'), ('kurigram', 'Kurigram'), ('lalmonirhat', 'Lalmonirhat'), ('nilphamari', 'Nilphamari'), ('panchagarh', 'Panchagarh'), ('rangpur', 'Rangpur'), ('thakurgaon', 'Thakurgaon'), ('barguna', 'Barguna'), ('barisal', 'Barisal'), ('bhola', 'Bhola'), ('jhalokati', 'Jhalokati'), ('patuakhali', 'Patuakhali'), ('pirojpur', 'Pirojpur'), ('bandarban', 'Bandarban'), ('brahmanbaria', 'Brahmanbaria'), ('chandpur', 'Chandpur'), ('chittagong', 'Chittagong'), ('comilla', 'Comilla'), ("cox's bazar", "Cox's bazar"), ('feni', 'Feni'), ('khagrachhari', 'Khagrachhari'), ('lakshmipur', 'Lakshmipur'), ('noakhali', 'Noakhali'), ('rangamati', 'Rangamati'), ('habiganj', 'Habiganj'), ('moulvibazar', 'Moulvibazar'), ('sunamganj', 'Sunamganj'), ('sylhet', 'Sylhet'), ('bagerhat', 'Bagerhat'), ('chuadanga', 'Chuadanga'), ('jessore', 'Jessore'), ('jhenaidah', 'Jhenaidah'), ('khulna', 'Khulna'), ('kushtia', 'Kushtia'), ('magura', 'Magura'), ('meherpur', 'Meherpur'), ('narail', 'Narail'), ('satkhira', 'Satkhira')], max_length=25, verbose_name='District')),
                ('account_phone', models.IntegerField()),
                ('billing_address', models.TextField()),
                ('organization_industry', models.CharField(choices=[('REAL ESTATE', 'REAL ESTATE'), ('SOFTWARE', 'SOFTWARE'), ('TECHNOLOGY', 'TECHNOLOGY'), ('FINANCE', 'FINANCE'), ('HEALTHCARE', 'HEALTHCARE'), ('INSURANCE', 'INSURANCE'), ('LEGAL', 'LEGAL'), ('MANUFACTURING', 'MANUFACTURING'), ('PUBLISHING', 'PUBLISHING'), ('TRANSPORTATION', 'TRANSPORTATION'), ('EDUCATION', 'EDUCATION'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('MEDIA', 'MEDIA'), ('TOURISM', 'TOURISM'), ('OTHER', 'OTHER')], help_text='Enter Organization Industry Type: ', max_length=255)),
                ('name_of_account', models.CharField(max_length=25, verbose_name='Name Of Account')),
                ('bank_account_number', models.IntegerField(verbose_name='Bank Account Number')),
                ('bank_name', models.CharField(max_length=25, verbose_name='Bank Name')),
                ('bank_branch', models.CharField(max_length=25, verbose_name='Bank Branch')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
