# Generated by Django 3.2.3 on 2021-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_description',
            field=models.TextField(verbose_name='Descrition'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=25, verbose_name='Name of Account'),
        ),
    ]
