# Generated by Django 3.2.5 on 2021-12-14 09:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210605_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(default='BD', max_length=2),
        ),
    ]
