# Generated by Django 3.2.5 on 2021-12-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=10, null=True),
        ),
    ]
