# Generated by Django 4.2.6 on 2023-10-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='net_total',
        ),
        migrations.RemoveField(
            model_name='service',
            name='total_tax',
        ),
        migrations.RemoveField(
            model_name='service',
            name='vat',
        ),
    ]
