# Generated by Django 4.2 on 2023-05-01 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('decsription', models.CharField(max_length=255, verbose_name='Description')),
                ('voucher_no', models.CharField(default='33851753441775', max_length=14, unique=True, verbose_name='Voucher No')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Credit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(default='+8801', max_length=128, region=None)),
                ('city', django_countries.fields.CountryField(default='BD', max_length=2)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_name'], name='customers_c_custome_1ff780_idx'),
        ),
    ]
