# Generated by Django 4.2.6 on 2023-10-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='voucher_no',
            field=models.CharField(default='85975767372210', max_length=14, unique=True, verbose_name='Voucher No'),
        ),
    ]
