# Generated by Django 3.2.3 on 2021-05-31 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
