# Generated by Django 4.2.6 on 2023-10-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_ledger_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='voucher_no',
            field=models.CharField(default='39579404005375', max_length=14, unique=True, verbose_name='Voucher No'),
        ),
    ]
