# Generated by Django 4.2.6 on 2023-10-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_ledger_voucher_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
