# Generated by Django 3.2.5 on 2021-12-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20211130_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_ledger',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_ledger',
            field=models.ManyToManyField(to='customers.Ledger'),
        ),
    ]
