# Generated by Django 3.2.5 on 2021-12-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20211201_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='voucher_no',
            field=models.CharField(default='753295064280608870', max_length=18, unique=True, verbose_name='Voucher No'),
        ),
    ]
