# Generated by Django 3.2.5 on 2021-12-14 09:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_ledger_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=django_countries.fields.CountryField(default='BD', max_length=2),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='voucher_no',
            field=models.CharField(default='87206188950438', max_length=14, unique=True, verbose_name='Voucher No'),
        ),
    ]
