# Generated by Django 3.2.5 on 2021-12-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20211214_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='voucher_no',
            field=models.CharField(default='09399799438579', max_length=14, unique=True, verbose_name='Voucher No'),
        ),
    ]
