# Generated by Django 3.2.5 on 2021-12-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20211216_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='voucher_no',
            field=models.CharField(default='97238539143609', max_length=14, unique=True, verbose_name='Voucher No'),
        ),
    ]
