# Generated by Django 3.2.5 on 2021-12-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_ledger_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='voucher_no',
            field=models.CharField(default='62634872914361', max_length=14, unique=True, verbose_name='Voucher No'),
        ),
    ]
