# Generated by Django 3.2.3 on 2021-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunity'},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='Opportunities_description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
