'''
In Bangladesh, we have offices in all eight administrative divisions. These divisions are divided into 64 districts.
'''

bangadesh_districts = (
    ('dhaka', 'Dhaka'),
    ('faridpur', 'Faridpur'),
    ('gazipur', 'Gazipur'),
    ('gopalganj', 'Gopalganj'),
    ('jamalpur', 'Jamalpur'),
    ('kishoreganj', 'Kishoreganj'),
    ('madaripur', 'Madaripur'),
    ('manikganj', 'Manikganj'),
    ('munshiganj', 'Munshiganj'),
    ('narayanganj', 'Narayanganj'),
    ('narsingdi', 'Narsingdi'),
    ('netrokona', 'Netrokona'),
    ('rajbari', 'Rajbari'),
    ('shariatpur', 'Shariatpur'),
    ('sherpur', 'Sherpur'),
    ('tangail', 'Tangail'),
    ('bogra', 'Bogra'),
    ('joypurhat', 'Joypurhat'),
    ('naogaon', 'Naogaon'),
    ('natore', 'Natore'),
    ('nawabganj', 'Nawabganj'),
    ('pabna', 'Pabna'),
    ('rajshahi', 'Rajshahi'),
    ('sirajganj', 'Sirajganj'),
    ('dinajpur', 'Dinajpur'),
    ('gaibandha', 'Gaibandha'),
    ('kurigram', 'Kurigram'),
    ('lalmonirhat', 'Lalmonirhat'),
    ('nilphamari', 'Nilphamari'),
    ('panchagarh', 'Panchagarh'),
    ('rangpur', 'Rangpur'),
    ('thakurgaon', 'Thakurgaon'),
    ('barguna', 'Barguna'),
    ('barisal', 'Barisal'),
    ('bhola', 'Bhola'),
    ('jhalokati', 'Jhalokati'),
    ('patuakhali', 'Patuakhali'),
    ('pirojpur', 'Pirojpur'),
    ('bandarban', 'Bandarban'),
    ('brahmanbaria', 'Brahmanbaria'),
    ('chandpur', 'Chandpur'),
    ('chittagong', 'Chittagong'),
    ('comilla', 'Comilla'),
    ('cox\'s bazar', 'Cox\'s bazar'),
    ('feni', 'Feni'),
    ('khagrachhari', 'Khagrachhari'),
    ('lakshmipur', 'Lakshmipur'),
    ('noakhali', 'Noakhali'),
    ('rangamati', 'Rangamati'),
    ('habiganj', 'Habiganj'),
    ('moulvibazar', 'Moulvibazar'),
    ('sunamganj', 'Sunamganj'),
    ('sylhet', 'Sylhet'),
    ('bagerhat', 'Bagerhat'),
    ('chuadanga', 'Chuadanga'),
    ('jessore', 'Jessore'),
    ('jhenaidah', 'Jhenaidah'),
    ('khulna', 'Khulna'),
    ('kushtia', 'Kushtia'),
    ('magura', 'Magura'),
    ('meherpur', 'Meherpur'),
    ('narail', 'Narail'),
    ('satkhira', 'Satkhira'),
)
