# Generated by Django 4.2 on 2023-05-01 06:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invoice_number', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('hand cash', 'Hand Cash'), ('cash on delivery', 'Cash On Delivery'), ('bKash', 'bKash'), ('উপায় (upay)', 'উপায় (upay)'), ('nagad', 'Nagad'), ('dutch-bangla bank', 'Dutch-Bangla Bank'), ('bank payment', 'Bank Payment')], max_length=50)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], max_length=50)),
                ('is_paid', models.BooleanField(default=False, help_text='Is the sale paid? If yes, the status will be set to paid.', verbose_name='Is Paid')),
                ('discount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        
    
    ]
