# Generated by Django 3.2.9 on 2021-12-23 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invoice_number', models.CharField(default='3781152169', max_length=10, unique=True)),
                ('date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('hand cash', 'Hand Cash'), ('cash on delivery', 'Cash On Delivery'), ('bKash', 'bKash'), ('উপায় (upay)', 'উপায় (upay)'), ('nagad', 'Nagad'), ('dutch-bangla bank', 'Dutch-Bangla Bank'), ('bank payment', 'Bank Payment')], max_length=50)),
                ('status', models.CharField(choices=[('পাওনা (unpaid)', 'পাওনা (UNPAID)'), ('পরিশোধ (paid)', 'পরিশোধ (PAID)')], max_length=50)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
