# Generated by Django 3.2.5 on 2021-12-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(default='7148165455', max_length=10, unique=True),
        ),
    ]
