# Generated by Django 3.2.5 on 2021-12-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211211_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='7705', max_length=4, unique=True),
        ),
    ]
